services:
  caddy:
    build:
      context: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - web
    environment:
      # Zone.Zone:Read and Zone.DNS:Edit
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /mnt/Docker/Data/Caddy/conf:/etc/caddy
      - /mnt/Docker/Data/Caddy/data:/data
      - /mnt/Docker/Data/Caddy/config:/config

      - /mnt/fourteen/Data/www:/mnt/fourteen/Data/www:ro
      - /mnt/fourteen/Data/DiscordEmbed:/mnt/fourteen/Data/DiscordEmbed:ro

      - /var/log/caddy:/var/log/caddy
networks:
  web:
    external: true
    name: web