---
services:
  anewdawn:
    container_name: anewdawn
    image: git.lovinator.space/thelovinator/anewdawn@sha256:22dac5fd2d5518d2f9cd5d4b3ff99c1e3009c79f14a5b88a152ca41340668278
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN?DISCORD_TOKEN is required}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY?DEEPSEEK_API_KEY is required}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY?OLLAMA_API_KEY is required}