---
networks:
  media:
    driver: bridge

  media_postgres:
    driver: bridge
    internal: true

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      media_postgres:
        condition: service_healthy
    ports:
      - "8888:80"
      - "8889:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    volumes:
      - /mnt/Docker/Data/Media/PGAdmin:/var/lib/pgadmin

  media_db_backup:
    container_name: media_db_backup
    image: ghcr.io/nfrastack/container-db-backup:4.9.0-alpine_3.24@sha256:eb36168ab9a37869583dc14c3f154fd31a57563cedfba0aba40278eb1fa7a1a6
    restart: always
    depends_on:
      media_postgres:
        condition: service_healthy
    environment:
      - TIMEZONE=Europe/Stockholm
      - USER_DBBACKUP=1000
      - GROUP_DBBACKUP=1000
      - DB01_TYPE=postgres
      - DB01_HOST=media_postgres
      - DB01_NAME=ALL
      - DB01_SPLIT_DB=TRUE
      - DB01_USER=backup
      - DB01_PASS=${POSTGRES_BACKUP_PASSWORD}
    networks:
      media_postgres:
        gw_priority: 0
    volumes:
      - /mnt/Fourteen/Data/Backup/Media/Database:/backup

  # MARK: Postgres
  media_postgres:
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    container_name: media_postgres
    image: postgres:18
    shm_size: 256m
    stop_grace_period: 1m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_SUPER_PASSWORD}
      - POSTGRES_SONARR_PASSWORD=${POSTGRES_SONARR_PASSWORD}
      - POSTGRES_RADARR_PASSWORD=${POSTGRES_RADARR_PASSWORD}
      - POSTGRES_BACKUP_PASSWORD=${POSTGRES_BACKUP_PASSWORD}
      - POSTGRES_PROWLARR_PASSWORD=${POSTGRES_PROWLARR_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 5
      timeout: 5s
      test:
        - CMD-SHELL
        - pg_isready --username sonarr --dbname sonarr_default_main
    networks:
      media_postgres:
        gw_priority: 0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /mnt/Docker/Data/Media/Postgres:/var/lib/postgresql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro

  # MARK: Prowlarr
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    read_only: true
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Europe/Stockholm
      - PROWLARR__POSTGRES__HOST=media_postgres
      - PROWLARR__POSTGRES__PORT=5432
      - PROWLARR__POSTGRES__USER=prowlarr
      - PROWLARR__POSTGRES__PASSWORD=${POSTGRES_PROWLARR_PASSWORD}
      - PROWLARR__POSTGRES__MAINDB=prowlarr_main
      - PROWLARR__POSTGRES__LOGDB=prowlarr_log
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    ports:
      - "9696:9696"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    volumes:
      - /mnt/Docker/Data/Media/Prowlarr:/config

  # MARK: Radarr
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:develop
    read_only: true
    restart: unless-stopped
    depends_on:
      media_postgres:
        condition: service_healthy
      prowlarr:
        condition: service_started
    environment:
      - TZ=Europe/Stockholm
      - RADARR__APP__INSTANCENAME=Radarr
      - RADARR__AUTH__APIKEY=${RADARR_API_KEY}
      - RADARR__POSTGRES__HOST=media_postgres
      - RADARR__POSTGRES__LOGDB=radarr_default_log
      - RADARR__POSTGRES__MAINDB=radarr_default_main
      - RADARR__POSTGRES__PASSWORD=${POSTGRES_RADARR_PASSWORD}
      - RADARR__POSTGRES__PORT=5432
      - RADARR__POSTGRES__USER=radarr
      - RADARR__SERVER__PORT=7878
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7878/api/v3/system/status?apikey=${RADARR_API_KEY}
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    ports:
      - "7878:7878"
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    volumes:
      - /mnt/Docker/Data/Media/Radarr/Default:/config
      - /mnt/fourteen/Data/Torrents:/mnt/fourteen/Data/Torrents

  radarr_anime:
    container_name: radarr_anime
    image: lscr.io/linuxserver/radarr:develop
    read_only: true
    restart: unless-stopped
    depends_on:
      media_postgres:
        condition: service_healthy
      prowlarr:
        condition: service_started
    environment:
      - TZ=Europe/Stockholm
      - RADARR__APP__INSTANCENAME=Radarr Anime
      - RADARR__AUTH__APIKEY=${RADARR_API_KEY}
      - RADARR__POSTGRES__HOST=media_postgres
      - RADARR__POSTGRES__LOGDB=radarr_anime_log
      - RADARR__POSTGRES__MAINDB=radarr_anime_main
      - RADARR__POSTGRES__PASSWORD=${POSTGRES_RADARR_PASSWORD}
      - RADARR__POSTGRES__PORT=5432
      - RADARR__POSTGRES__USER=radarr
      - RADARR__SERVER__PORT=7879
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7879/api/v3/system/status?apikey=${RADARR_API_KEY}
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    ports:
      - "7879:7879"
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    volumes:
      - /mnt/Docker/Data/Media/Radarr/Anime:/config
      - /mnt/fourteen/Data/Torrents:/mnt/fourteen/Data/Torrents

  # MARK: Recyclarr
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:8
    read_only: true
    restart: unless-stopped
    tmpfs: /tmp
    user: 1000:1000
    environment:
      - TZ=Europe/Stockholm
      - RECYCLARR_CREATE_CONFIG=true
    networks:
      media:
        gw_priority: 100
    security_opt:
      - no-new-privileges:true
    volumes:
      - /mnt/Docker/Data/Media/Recyclarr:/config

  # MARK: Sonarr
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:develop
    read_only: true
    restart: unless-stopped
    stop_grace_period: 1m
    depends_on:
      media_postgres:
        condition: service_healthy
      prowlarr:
        condition: service_started
    environment:
      - TZ=Europe/Stockholm
      - SONARR__APP__INSTANCENAME=Sonarr
      - SONARR__AUTH__APIKEY=${SONARR_API_KEY}
      - SONARR__POSTGRES__HOST=media_postgres
      - SONARR__POSTGRES__LOGDB=sonarr_default_log
      - SONARR__POSTGRES__MAINDB=sonarr_default_main
      - SONARR__POSTGRES__PASSWORD=${POSTGRES_SONARR_PASSWORD}
      - SONARR__POSTGRES__PORT=5432
      - SONARR__POSTGRES__USER=sonarr
      - SONARR__SERVER__PORT=8989
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8989/api/v3/system/status?apikey=${SONARR_API_KEY}
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    ports:
      - "8989:8989"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    volumes:
      - /mnt/Docker/Data/Media/Sonarr/Default:/config
      - /mnt/fourteen/Data/Torrents:/mnt/fourteen/Data/Torrents

  sonarr_anime:
    container_name: sonarr_anime
    image: lscr.io/linuxserver/sonarr:develop
    read_only: true
    restart: unless-stopped
    depends_on:
      media_postgres:
        condition: service_healthy
      prowlarr:
        condition: service_started
    environment:
      - TZ=Europe/Stockholm
      - SONARR__APP__INSTANCENAME=Sonarr Anime
      - SONARR__AUTH__APIKEY=${SONARR_API_KEY}
      - SONARR__POSTGRES__HOST=media_postgres
      - SONARR__POSTGRES__LOGDB=sonarr_anime_log
      - SONARR__POSTGRES__MAINDB=sonarr_anime_main
      - SONARR__POSTGRES__PASSWORD=${POSTGRES_SONARR_PASSWORD}
      - SONARR__POSTGRES__PORT=5432
      - SONARR__POSTGRES__USER=sonarr
      - SONARR__SERVER__PORT=8990
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8990/api/v3/system/status?apikey=${SONARR_API_KEY}
    networks:
      media:
        gw_priority: 100
      media_postgres:
        gw_priority: 0
    ports:
      - "8990:8990"
    tmpfs:
      - /run:uid=1000,gid=1000,exec
    volumes:
      - /mnt/Docker/Data/Media/Sonarr/Anime:/config
      - /mnt/fourteen/Data/Torrents:/mnt/fourteen/Data/Torrents
