services:
  cloudflare_ddns:
    image: favonia/cloudflare-ddns:1
    container_name: cloudflare_ddns
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN?Add Cloudflare API token to .env file}
      - DOMAINS=lovinator.space,*.lovinator.space,feedvault.se,*.feedvault.se,panso.se,*.panso.se,tussilago.dev,*.tussilago.dev