---
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/qbittorrent/docker-qbittorrent-nox:latest
    network_mode: host
    read_only: true
    restart: unless-stopped
    stop_grace_period: 30m
    tty: true
    user: 1000:1000
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_TORRENTING_PORT=22799
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - TZ=Europe/Stockholm
      - UMASK=022
    tmpfs:
      - /tmp
    volumes:
      - /mnt/Docker/Data/qBittorrent:/config
      - /mnt/fourteen/Data/Torrents:/mnt/fourteen/Data/Torrents
...
